name: SPM

on: push

jobs:
 build:
  runs-on: self-hosted
  steps:
   - uses: actions/checkout@v2
   - name: Checkout
     run: |
   - name: Setup Environment
     run: bundle install 
   - name: Test
     run: bundle exec fastlane unit_tests 
