name: SPM

on: push

jobs:
 build:
  runs-on: macos-latest
  steps:
  - name: Build with code signing
    uses: maierj/fastlane-action@v0.10.0
    with:
     lane: build
     subdirectory: flutter_app/ios
