name: SPM

on: push

jobs:
 build:
  runs-on: self-hosted
  steps:
   - name: Checkout
   - uses: actions/checkout@master
     with:
      ref: ${{ github.ref }}
   - name: Setup Environment
     run: bundle install 
   - name: Test
     run: bundle exec fastlane unit_tests 
